name: Build Native Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: demo
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U demo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17.0.12'
          distribution: 'graalvm'

      - name: Build native Docker image
        run: ./mvnw -Pnative spring-boot:build-image
