name: Build Native Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'graalvm'

      - name: Build native Docker image
        run: ./mvnw -Pnative spring-boot:build-image
